### ISSUE TITLE
Adding CometLLM

### ISSUE THREAD

**Issue by anmorgan24** [snwfdhmp/awesome-gpt-prompt-engineering#13]
- Resource Name: CometLLM
- Resource Type: opensource tool
- Link: https://github.com/comet-ml/comet-llm
- Description: Track, visualize, and evaluate your LLM prompts and chains in one simple-to-use, convenient UI.

**Comment by snwfdhmp** [comment]
Thanks ! Can you make a PR ?

**Comment by anmorgan24** [comment]
Absolutely! Was just following the instructions in the contributing.md by submitting an issue :) PR submitted! Thanks!
