### ISSUE TITLE
Understanding Prompt Injections and What You Can Do About Them

### ISSUE THREAD

**Issue by Dan-Cleary** [snwfdhmp/awesome-gpt-prompt-engineering#2]
Resource Name: Understanding Prompt Injections and What You Can Do About Them
Resource Type: Guide
Link: https://www.prompthub.us/blog/understanding-prompt-injections-and-what-you-can-do-about-them
Description: An introduction to prompt injections with examples and tactics you can use to mitigate potential risks in your application!

**Comment by snwfdhmp** [comment]
Added !
