### ISSUE TITLE
New resource

### ISSUE THREAD

**Issue by Dan-Cleary** [snwfdhmp/awesome-gpt-prompt-engineering#6]
Resource Name: Tokens and Tokenization: Understanding Cost, Speed, and Limits with OpenAI's APIs
Resource Type: Guide
Link: https://www.prompthub.us/blog/tokens-and-tokenization-understanding-cost-speed-and-limits-with-openais-apis
Description: Everything tokens and tokenization. How to control costs/performance, how to handle Max token limits, and a real-world example on how you can make your prompts more efficient

**Comment by snwfdhmp** [comment]
hey ! thanks for your help. Can you create a PR ?

**Comment by Dan-Cleary** [comment]
Done!
